[features]
seeds = true
skip-lint = false
[programs.localnet]
dapp01_1 = "A1WQcJ7w8QPmyUmjUtfsvVMk47pCYcXSFf9hZq7mRwUF"

[programs.devnet]
dapp01_1 = "A1WQcJ7w8QPmyUmjUtfsvVMk47pCYcXSFf9hZq7mRwUF"

[programs.testnet]
dapp01_1 = "A1WQcJ7w8QPmyUmjUtfsvVMk47pCYcXSFf9hZq7mRwUF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
testnet = "yarn run testnet"

